Correct bug seen in java.io.ObjectInputStream.inputArray() when compiling FLEX with itself: QuadClassHierarchy when given quad-with-try form as input did not count TYPECASTs as naming a class to be discovered, even though they would be turned into INSTANCEOF quads which would reference that class during the conversion to quad-no-ssa.  This caused an undefined reference to _Class__3F in the output in the above method.
This bug is now fixed: the type mentioned in a TYPECAST is properly
discovered, just as if it were an INSTANCEOF.