We don't catch the NoClassDefFoundError that Class.forName() may throw when translating a static synchronized method.  The definition of exC made it look like we were gonna do it, but we don't.  If we need to, then this code should be uncommented again.