Add createMutableClass() method to Linker and Relinker.
Documentation updates to Relinker.relink().

Changed exception thrown by Linker.forName(), etc, from
NoClassDefFoundError to new NoSuchClassException, as the
condition ought really be a RuntimeException, not an Error.